image: Visual Studio 2017

configuration:
- Release

before_build:
- nuget restore src\WebDriverManagerSharp.sln

build:
  project: src\WebDriverManagerSharp.sln
  verbosity: minimal

test:
  assemblies:
    only:
      - WebDriverManagerSharp.UnitTests.dll

test_script:
- src\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:appveyor -target:"nunit3-console" -targetargs:"src\WebDriverManagerSharp.UnitTests\bin\Release\WebDriverManagerSharp.UnitTests.dll --result=results.xml --result=results-appveyor.xml;format=AppVeyor" -filter:"+[WebDriverManagerSharp*]* -[WebDriverManagerSharp.UnitTests*]*" -output:".\coverage.xml"

after_test:
- ps: |
    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
    bash codecov.sh -f "coverage.xml"
